version: "3.7"

networks:
  network_auth:


services:

  app:
    build:
      args:
        user: eduardo
        uid: 1000
        context: ./
        dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../volumen/app:/var/www
    networks:
      - network_auth

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbusuario
      MYSQL_ROOT_PASSWORD: eduardo
      MYSQL_PASSWORD: eduardo
      MYSQL_USER: eduardo
    networks:
      - network_auth

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../volumen/app:/var/www
      - ../volumen/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network_auth
